import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Utility to export data as branded PDF files for local download.
 * Includes business logo, name, and contact info in every export.
 */

/** Get business info from localStorage/user for branding exports */
function getBusinessInfo() {
  const logo = localStorage.getItem('appLogo') || '';
  let businessName = '';
  let email = '';
  try {
    const user = JSON.parse(localStorage.getItem('user') || '{}');
    businessName = user.businessName || user.business_name || user.name || '';
    email = user.email || '';
  } catch { /* ignore */ }
  return { logo, businessName, email };
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  try {
    return new Date(dateStr).toLocaleString();
  } catch {
    return String(dateStr);
  }
}

/**
 * Create a branded PDF with logo header, title, and auto-table.
 */
function buildPDF(title, headers, rows, summaryLines = [], options = {}) {
  const { logo, businessName, email } = getBusinessInfo();
  const orientation = options.landscape ? 'landscape' : 'portrait';
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 15;

  // --- Logo ---
  if (logo) {
    try {
      doc.addImage(logo, 'PNG', 14, yPos - 5, 25, 25);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(businessName || 'Business Report', 44, yPos + 4);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      if (email) doc.text(email, 44, yPos + 10);
      doc.text(`${title}  —  ${new Date().toLocaleDateString()}`, 44, yPos + (email ? 16 : 10));
      yPos += 28;
    } catch {
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(businessName || title, 14, yPos + 4);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      if (email) doc.text(email, 14, yPos + 10);
      doc.text(`${title}  —  ${new Date().toLocaleDateString()}`, 14, yPos + (email ? 16 : 10));
      yPos += 22;
    }
  } else {
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(businessName || title, 14, yPos + 4);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    if (email) doc.text(email, 14, yPos + 10);
    doc.text(`${title}  —  ${new Date().toLocaleDateString()}`, 14, yPos + (email ? 16 : 10));
    yPos += 22;
  }

  // --- Blue divider ---
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.8);
  doc.line(14, yPos, pageWidth - 14, yPos);
  yPos += 6;

  // --- Table ---
  doc.autoTable({
    head: [headers],
    body: rows.map(row => row.map(cell => (cell != null ? String(cell) : ''))),
    startY: yPos,
    theme: 'grid',
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: { fontSize: 8, textColor: [51, 51, 51] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: {
      cellPadding: 3,
      lineColor: [226, 232, 240],
      lineWidth: 0.3,
      overflow: 'linebreak'
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}  |  Generated by POSifine`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: 'center' }
      );
    }
  });

  // --- Summary ---
  if (summaryLines.length > 0) {
    let summaryY = doc.lastAutoTable.finalY + 10;
    if (summaryY + summaryLines.length * 7 > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      summaryY = 20;
    }
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, summaryY - 4, pageWidth - 28, summaryLines.length * 7 + 12, 3, 3, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Summary', 20, summaryY + 4);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    summaryLines.forEach((line, i) => {
      doc.text(line, 20, summaryY + 12 + i * 7);
    });
  }

  return doc;
}

// ===== SALES =====

export function exportSalesPDF(sales) {
  const headers = ['ID', 'Date', 'Items', 'Payment', 'Cashier', 'Total (KSH)', 'COGS (KSH)', 'Profit (KSH)'];
  const totalSales = sales.reduce((s, sale) => s + (sale.total || 0), 0);
  const totalCOGS = sales.reduce((s, sale) => s + (sale.cogs ?? sale.total_cost ?? 0), 0);
  const totalProfit = totalSales - totalCOGS;

  const rows = sales.map(sale => {
    const cogs = sale.cogs ?? sale.total_cost ?? 0;
    const profit = sale.profit ?? sale.gross_profit ?? (sale.total || 0) - cogs;
    const itemNames = (sale.items || []).map(i => `${i.name || '?'} x${i.quantity || 1}`).join(', ');
    return [
      sale.id,
      formatDate(sale.createdAt || sale.created_at),
      itemNames,
      sale.paymentMethod || sale.payment_method || '',
      sale.cashier_name || sale.cashierName || '',
      `KSH ${(sale.total || 0).toLocaleString()}`,
      `KSH ${cogs.toLocaleString()}`,
      `KSH ${profit.toLocaleString()}`
    ];
  });

  const summary = [
    `Total Sales: KSH ${totalSales.toLocaleString()}`,
    `Total COGS: KSH ${totalCOGS.toLocaleString()}`,
    `Net Profit: KSH ${totalProfit.toLocaleString()}`,
    `Transactions: ${sales.length}`
  ];

  const doc = buildPDF('Sales Report', headers, rows, summary, { landscape: true });
  doc.save(`sales-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function exportSalesDetailedPDF(sales) {
  const headers = ['Sale ID', 'Date', 'Item', 'Qty', 'Price (KSH)', 'Subtotal (KSH)', 'Payment', 'Cashier'];
  const rows = [];
  sales.forEach(sale => {
    if (sale.items && sale.items.length > 0) {
      sale.items.forEach(item => {
        rows.push([
          sale.id,
          formatDate(sale.createdAt || sale.created_at),
          item.name || '',
          item.quantity || 0,
          `KSH ${(item.price || 0).toLocaleString()}`,
          `KSH ${((item.price || 0) * (item.quantity || 0)).toLocaleString()}`,
          sale.paymentMethod || sale.payment_method || '',
          sale.cashier_name || sale.cashierName || ''
        ]);
      });
    }
  });

  const totalSales = sales.reduce((s, sale) => s + (sale.total || 0), 0);
  const summary = [
    `Total Revenue: KSH ${totalSales.toLocaleString()}`,
    `Total Items Sold: ${rows.length}`,
    `Transactions: ${sales.length}`
  ];

  const doc = buildPDF('Detailed Sales Report', headers, rows, summary, { landscape: true });
  doc.save(`sales-detailed-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ===== EXPENSES =====

export function exportExpensesPDF(expenses) {
  const headers = ['ID', 'Date', 'Description', 'Category', 'Source', 'Amount (KSH)', 'Qty', 'Unit'];
  const totalExpenses = expenses.reduce((s, e) => s + (e.amount || 0), 0);
  const rows = expenses.map(exp => [
    exp.id,
    formatDate(exp.created_at || exp.createdAt),
    exp.description || '',
    exp.category || '',
    exp.source || 'manual',
    `KSH ${(exp.amount || 0).toLocaleString()}`,
    exp.quantity || '',
    exp.unit || ''
  ]);

  const summary = [
    `Total Expenses: KSH ${totalExpenses.toLocaleString()}`,
    `Total Entries: ${expenses.length}`
  ];

  const doc = buildPDF('Expenses Report', headers, rows, summary);
  doc.save(`expenses-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ===== VENDORS =====

export function exportVendorsPDF(vendors) {
  const headers = ['Name', 'Email', 'Phone', 'Address', 'City', 'Country', 'Products'];
  const rows = vendors.map(v => [
    v.name || '',
    v.email || '',
    v.phone || '',
    v.address || '',
    v.city || '',
    v.country || '',
    v.products || ''
  ]);

  const summary = [`Total Vendors: ${vendors.length}`];
  const doc = buildPDF('Vendors Report', headers, rows, summary, { landscape: true });
  doc.save(`vendors-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ===== ANALYTICS =====

export function exportAnalyticsPDF(productStats, summaryStats) {
  const headers = ['Product Name', 'Quantity Sold', 'Revenue (KSH)', 'Profit (KSH)', 'Times Sold'];
  const rows = productStats.map(p => [
    p.name,
    p.quantity,
    `KSH ${(p.revenue || 0).toLocaleString()}`,
    `KSH ${(p.profit || 0).toLocaleString()}`,
    p.count
  ]);

  const summary = [
    `Total Revenue: KSH ${(summaryStats.totalRevenue || 0).toLocaleString()}`,
    `Total Profit: KSH ${(summaryStats.totalProfit || 0).toLocaleString()}`,
    `Profit Margin: ${(summaryStats.profitMargin || 0).toFixed(1)}%`,
    `Transactions: ${summaryStats.totalTransactions || 0}`,
    `Avg Transaction: KSH ${(summaryStats.avgTransaction || 0).toFixed(0)}`
  ];

  const doc = buildPDF('Analytics Report', headers, rows, summary);
  doc.save(`analytics-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ===== STOCK =====

export function exportStockPDF(products, ingredientStocks) {
  const headers = ['Name', 'Type', 'Quantity', 'Unit', 'Cost/Unit (KSH)', 'Price (KSH)', 'Status'];
  const rows = [];

  if (products && products.length > 0) {
    products.forEach(p => {
      const qty = p.quantity ?? p.stock ?? 0;
      rows.push([
        p.name || '',
        'Product',
        qty,
        p.unit || 'pcs',
        p.cost_per_unit ?? p.cost ?? '',
        p.price ?? p.selling_price ?? '',
        qty <= 0 ? 'Out of Stock' : 'In Stock'
      ]);
    });
  }

  if (ingredientStocks && ingredientStocks.length > 0) {
    ingredientStocks.forEach(m => {
      const qty = Number(m.quantity || 0);
      const reorder = Number(m.reorder_level || 0);
      rows.push([
        m.name || '',
        'Ingredient',
        qty,
        m.unit || 'units',
        m.cost_per_unit ?? '',
        '',
        reorder > 0 && qty <= reorder ? 'Low Stock' : 'In Stock'
      ]);
    });
  }

  const inStock = rows.filter(r => r[6] === 'In Stock').length;
  const lowStock = rows.filter(r => r[6] === 'Low Stock').length;
  const outOfStock = rows.filter(r => r[6] === 'Out of Stock').length;
  const summary = [
    `Total Items: ${rows.length}`,
    `In Stock: ${inStock}`,
    `Low Stock: ${lowStock}`,
    `Out of Stock: ${outOfStock}`
  ];

  const doc = buildPDF('Stock & Inventory Report', headers, rows, summary);
  doc.save(`stock-inventory-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ===== CREDIT REQUESTS =====

export function exportCreditRequestsPDF(requests) {
  const headers = ['Date', 'Customer', 'Amount (KSH)', 'Reason', 'Status', 'Cashier', 'Admin Notes'];
  const rows = requests.map(r => [
    formatDate(r.created_at || r.createdAt),
    r.customer_name || r.customerName || '',
    `KSH ${(r.amount || 0).toLocaleString()}`,
    r.reason || '',
    r.status || '',
    r.cashier_name || r.cashierName || '',
    r.admin_notes || r.rejectionReason || ''
  ]);

  const total = requests.reduce((s, r) => s + (r.amount || 0), 0);
  const pending = requests.filter(r => r.status === 'pending').length;
  const approved = requests.filter(r => r.status === 'approved').length;
  const rejected = requests.filter(r => r.status === 'rejected').length;
  const summary = [
    `Total Amount: KSH ${total.toLocaleString()}`,
    `Pending: ${pending}`,
    `Approved: ${approved}`,
    `Rejected: ${rejected}`
  ];

  const doc = buildPDF('Credit Requests Report', headers, rows, summary);
  doc.save(`credit-requests-${new Date().toISOString().slice(0, 10)}.pdf`);
}
